# Generated by Django 3.2 on 2022-08-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_staffprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='org',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='org',
            field=models.ManyToManyField(to='organisation.OrgProfile'),
        ),
    ]
