# Generated by Django 3.2 on 2022-08-12 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_auto_20220812_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='org',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organisation.orgprofile'),
            preserve_default=False,
        ),
    ]
