# Generated by Django 3.2.4 on 2021-06-10 14:18

from django.db import migrations, models
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.CharField(default=school.models.code, editable=False, max_length=6, unique=True),
        ),
    ]
