# Generated by Django 3.2 on 2023-02-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_org',
            field=models.BooleanField(default=False, verbose_name='is organisation'),
        ),
    ]
